import React from "react";
import Head from "next/head";
import Link from "next/link";
import { motion } from "framer-motion";
import {signIn} from "next-auth/react";
import Image from "next/image";
import cm from "../public/cm.jpeg";
import exec from "../public/execsecurity.jpeg";
import cctv from "../public/cctv.jpeg";
import cctv1 from "../public/cctv1.jpeg";
import ctv1 from "../public/ctv1.jpeg";
import ctv2 from "../public/ctv2.jpeg";
import ctv3 from "../public/ctv3.jpeg";
import ctv4 from "../public/ctv4.jpeg";
import smen from "../public/smen.jpeg";
import smen1 from "../public/smen1.jpeg";

function about() {
  return (
    <>
      <Head>
        <title>About | GLERA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <main className="xs:mx-32 mx-10">
        <section
          id="hero"
          className="xs:h-min"
          style={{
            backgroundImage: "url('/gle.png')",
            backgroundRepeat: "no-repeat",
            backgroundPosition: "center",
            backgroundSize: "cover",
          }}
        > 
          <h1 className="text-center font-extrabold xs:text-[28px] tracking-wider pt-5 text-green-600">ABOUT</h1>
          <div className="flex justify-center m-auto pb-5">
            <Image src="/logo1.png" alt="" width={200} height={100}/>
          </div>
        </section>
        
        <motion.h1
          initial={{ opacity: 0, scale: 0.5 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 1.0 }}
          className="pt-5 text-center text-green-600 text-[40px] underline"
        >
          
        </motion.h1>
        <motion.div
          initial={{ opacity: 0, scale: 0.5 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 2.0 }}
          className="pt-5"
        >
          <h1 className="text-[18px] font-bold pb-5">BRIEF BACKGROUND REPORT</h1>
          <p className="text-[13px]">
            <b className="text-[14px]">GREENLAND RESIDENTS COMMUNITY DEVELOPMENT ASSOCIATION (GRCDA)</b>. 
            Greenland Estate Residents Association was originally named and address as Olokonla village, Ajah.
            There were no village/Community dwellers but a group of individuals who bought their own landed properties directly from Olokonla & Olumegbon family.
            These individuals decided to come together and form a voluntary association named Greenland Estate Residents Association (GLERA) duly registered with the Corporate Affairs Commission (CAC). 
            Years later Greenland Residents Association decided to transmute into CDA and this was duly registered as GREENLAND RESIDENT Community Development Association with Eti Osa East Local Development Council Area, 
            Lagos State on 30th October, 2012 with Registration number: EDELCDA/AR&SI.63VOL1-GRCDA. 
            <br />
            <br /><b className="text-[14px]">Greenland Resident Community Development Association</b> was equally registered at the State government level under the Ministry of Local Government And Community Affairs, Alausa, Ikeja.
            Greenland Resident Community Development Association has since inception witnessed four (4) successful regimes: 1st was headed by late Chief Abimbola Everett, 2nd was Chief Emmanuel Ileka, 3rd Captain Mbah and
            the 4th is the incumbent Chairman, Prince Adewale Taorid Ojora FICSSM FCICN and members of his cabinet includes: Comrade John Nwanosike (VC)
            Uzoegbu Donatus (General Secretary)
            Chineye Egbo (Mrs) Treasurer and Committee members. <br />
            Since inception, Greenland Residents Association CDA have solely undertaken all its developmental projects which includes the following:
            ROAD CONSTRUCTION:
            Residents has been saddled with the responsibility of grading and Sand filling of all it's existing 10 roads network. Construction of drainages, 14 Culverts 
            to address the peculiar problem of flood and equally started interlocking three major roads out of the 10 roads. 
          </p>
        </motion.div>
        <motion.div
          initial={{ opacity: 0, scale: 0.5 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 2.0 }}
          className="pt-4 min-w-min"
        >
          <p className="text-[18px] font-bold underline">ELECTRICITY</p>
          <span className="text-[13px]">
            Electricity has been a long term project being embarked upon by the residents. We started by providing electricity wooden Poles gradually which we later replaced with Concrete Poles, as at today, we have 125 electric poles. 
            We procured four (4) Transformers through levies and personal donations by residents from 2003 to 2022 , out of which the two (2) Nos brand new 500KVA 33 transformer was purchased between 2021 and 2022 to replace the 2 obsolete Transformers and efforts are still being made to add two (2) addditional 500 KVA 33 transformer in the couple of months to bring to total of four (4) brand new transformer within the CDA.
            All the current transformers in use numbering two were directly purchased by the residents and formally handed over to EKEDC for installation and energizing.
          </span>
        </motion.div>
        <motion.div
          initial={{ opacity: 0, scale: 0.5 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 2.0 }}
          className="pt-4 min-w-min"
        >
          <p className="text-[18px] font-bold underline">SECURITY</p>
          <span className="text-[13px]">
            Residents Association provides it's own trained security personnel and compliments with the engagement of vigilante group. In all, we have a total number of 18 operatives covering both day and night under our payroll.
            Equipping the Security operatives and continued enhancement of our overall security architecture has been a routine responsibility and exercise treated with priority. 
            Security Equipment And Uniforms: The Security operatives are well equipped with all necessary gadgets including Walkie Talkies, Hardwares etc
            OFFICE CLEANERS:
            We have four (4) Cleaners under our payroll who ensure that the surroundings are kept clean at all times.
            In addition, the environment is usually sanitized and fumigated from time to time.
            We also patronize the services of LAWMA (PSP) in accordance with the State government regulations.
          </span>
        </motion.div>
        <motion.div
          initial={{ opacity: 0, scale: 0.5 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 2.0 }}
          className="pt-4 min-w-min"
        >
          <p className="text-[18px] font-bold underline">STREET LIGHTS</p>
          <span className="text-[13px]">
          For better illumination and security purposes, residents Association decided to provide street lights to some of the roads and that has been ongoing..
          </span>
        </motion.div>
        <motion.div
          initial={{ opacity: 0, scale: 0.5 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 2.0 }}
          className="pt-4 min-w-min"
        >
          <p className="text-[18px] font-bold underline">SOLAR AND INVERTER</p>
          <span className="text-[13px]">
            The residents Association recently procured and installed a 5KVA Solar/Inverter power generation system with 12 Solar Panels and 12 Solar Batteries to boost power supply in the Estate. The residents have continued to experience the problems of incessant outages and collapse of national grid that threw the entire community into total darkness. The Solar also powered both the street light and the Secretarial offices.
            PROVISION OF 2Nos Solar Panel Max Power 18v 80W (high efficiency
            monocrystalline silicon) 
          </span>
        </motion.div>
        <motion.div
          initial={{ opacity: 0, scale: 0.5 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 2.0 }}
          className="pt-4 min-w-min"
        >
          <p className="text-[18px] font-bold underline">CCTV</p>
          <span className="text-[13px]">
          Our quest to enhance security architecture prompted us to acquire two (2) units Solar powered CCTV which was installed on road 1 entrance and road 2 entrance respectively. Efforts are being made to procure additional 10-CCTV before the year ends.
          </span>
        </motion.div>
        
        <div className="xs:grid xs:grid-cols-5 items-center">
          <div>
            <Image src={cm} alt="" width={200} className="rounded-full drop-shadow-lg pb-2"/>
            <h1 className="font">Current Chairman</h1>
            <p>Prince Adewale Taorid Ojora</p>
            <span>FICSSM FCICN</span>
          </div>
          <div className="xs:col-span-4 text-[12px] xs:text-[12px] xs:mt-10 md:text-[16px] mv:pt-5">
            <h1 className="text-green-700 font-bold text-lg">CHAIRMAN'S ACCEPTANCE SPEECH</h1>
            <p>
              Members of the Board of Trustees of our serene and great Estate,Members of the past EXCO, Members of the newly elected EXCO, The elders, 
              The land owning families ( Olumegbon & Olokonla) who are our traditional/ customary landlords,
              And of course all landlords & residents of the estate. 
              <span className="text-green-700 font-bold"> Congratulations Fellow Greenlanders</span> on this milestone achievement of emerging a stronger & better Greenland Estate from a keenly contested electioneering process.
              The outcome of this election is a victory for integrity, accountability, transparency, Victory for the rule of law, 
              Victory for all progressive minded Greenlanders who stood firm in upholding all known democratic principles in defense of our estate constitution which is the basis for our collective corporate existence as a legal entity .
              I salute the courage, dedication & commitment of our BOT led by Pastor Awelle Okonkwo in managing the situation effectively and ensuring timely completion of the democratic process.
              This is the birth of a new era in the administration of Greenland Estate. I stand here as the 5th elected chairman of Greenland Estate and 
              express my heart felt appreciation to everyone that has made this moment worthwhile for us to be able to gather again for the singular purpose of taking our estate to greater heights.
              While we are not oblivious of the recent developments in the estate,  it’s a long walk to freedom and institutionalized democracy .I hasten to emphasise that this election was geared towards having a more robust , cleaner , well organized and better community . I therefore take this election victory as a call to service and accountability of purpose.
              As leaders in our respective callings,  we occasionally find ourselves in situations that require we add to our proficiencies or we are faced with new experiences and opportunities  to propel a new thinking.
              However, the good thing in community relationships and community leadership is to be innovative and continuously hit the bulls eye for value added services, both in residential content and environmental aesthetics.
              Please let me state quickly that I will not shy away from the fact that we have to build on the successes of the past executives since inception of our estate. The honour is also for us to address any shortcomings and fill in the gaps.
              At this juncture, I wish to reiterate my firm commitment to our seven(7) points agenda tagged GEESIIF which is geared towards uplifting of all spheres of our estate.
              It is a clarion call that we all come on board to make this a reality and  achieve this purpose for the benefit of all.
              We will ensure monthly publication of the estate account and organize a quarterly town hall meeting for the presentation of stewardship of our administration in-line with our core values of integrity, accountability and transparency.
            </p>
          </div>
        </div>
        
        <div>
          <h1 className="text-center font-bold tracking-tighter text-[18px] xs:text-[22px] p-10">GLERA GALLERY</h1>
          <h1 className="text-center font-bold tracking-tighter text-[16px] xs:text-[20px] pb-5">On Security Matter.</h1>
          <div className="xs:grid xs:grid-cols-3 items-center gap-3">
            <div className="text-[12px] pb-5 text-center">
              <Image src={exec} alt="Greenland EstateCCTV" width={600} className="drop-shadow-lg rounded-lg pb-2"/>
              <p className="text-[10] xs:text-[10px] md:text-[14px] italic">Estate Exco Visit to Police
              <br /><span className="italic">Ajiwe Police station</span>
              </p>
            </div>
            <div className="text-[12px] pb-5 text-center">
              <Image src={smen} alt="Greenland EstateCCTV" width={600} className="drop-shadow-lg rounded-lg pb-2"/>
              <p className="text-[10] xs:text-[10px] md:text-[14px] italic">Greenland Estate Security Men</p>
            </div>
            <div className="text-[12px] pb-5 text-center">
              <Image src={smen1} alt="Greenland EstateCCTV" width={600} className="drop-shadow-lg rounded-lg pb-2"/>
              <p className="text-[10] xs:text-[10px] md:text-[14px]">Estate Manager and Security officers</p>
            </div>
          </div>
        </div>

        <div className="pt-10">
          <h1 className="text-center font-bold tracking-widest text-[16px] xs:text-[20px] pb-5">CCTV</h1>
          <p className="text-[12px] xs:text-[12px] md:text-[14px] italic pb-5">
            Hello fellow Greenlanders, We're pleased to inform you that the Executive Committee 
            have just taken delivery of 10-Units HD Intelligent Solar Energy Alert PTZ (CCTV) Cameras from SMARTCITY. 
            You would recalled that the Chairman in his speech at the congress held on the 18th February, 2023 highlighted
            some of the CSR projects brokered during our continuous engagement with the management of SMARTCITY. 
            This will further enhance our present security position. Meanwhile, arrangements has been concluded for immediate installation.
            Thanks for your continued support and cooperation. <br /> Signed ✍️ GENERAL SECRETARY
          </p>
          <div className="xs:grid xs:grid-cols-3 items-center gap-3">
            <div className="text-[12px] pb-5 text-center">
              <Image src={cctv} alt="Greenland EstateCCTV" width={600} className="drop-shadow-lg rounded-lg pb-2"/>
            </div>
            <div className="text-[12px] pb-5 text-center">
              <Image src={cctv1} alt="Greenland EstateCCTV" width={600} className="drop-shadow-lg rounded-lg pb-2"/>
            </div>
            <div className="text-[12px] pb-5 text-center">
              <Image src={ctv4} alt="Greenland EstateCCTV" width={600} className="drop-shadow-lg rounded-lg pb-2"/>
            </div>
          </div>
        </div>

        <div className="pt-10">
          <div className="xs:grid xs:grid-cols-3 items-center gap-3">
            <div className="text-[12px] pb-5 text-center">
              <Image src={ctv1} alt="Greenland EstateCCTV" width={600} className="drop-shadow-lg rounded-lg pb-2"/>
            </div>
            <div className="text-[12px] pb-5 text-center">
              <Image src={ctv2} alt="Greenland EstateCCTV" width={600} className="drop-shadow-lg rounded-lg pb-2"/>
            </div>
            <div className="text-[12px] pb-5 text-center">
              <Image src={ctv3} alt="Greenland EstateCCTV" width={600} className="drop-shadow-lg rounded-lg pb-2"/>
            </div>
          </div>
        </div>

        <div className="pt-10">
          <h1 className="text-center font-bold tracking-widest text-[16px] xs:text-[20px] pb-5"></h1>
          <div className="xs:grid xs:grid-cols-3 items-center gap-3">
            <div className="text-[12px] pb-5 text-center">
              <Image src={cctv} alt="Greenland EstateCCTV" width={600} className="drop-shadow-lg rounded-lg pb-2"/>
            </div>
            <div className="text-[12px] pb-5 text-center">
              <Image src={cctv1} alt="Greenland EstateCCTV" width={600} className="drop-shadow-lg rounded-lg pb-2"/>
            </div>
            <div className="text-[12px] pb-5 text-center">
              <Image src={ctv4} alt="Greenland EstateCCTV" width={600} className="drop-shadow-lg rounded-lg pb-2"/>
            </div>
          </div>
        </div>

      </main>
    </>
  );
}

export default about;
