import Head from "next/head";
import { motion } from "framer-motion";
import Link from "next/link";
import Image from "next/image";
import card from "../public/logo.png";
import call from "../public/call.svg";
import cm from "../public/cm.jpeg";
import exec from "../public/exec.jpeg";
import execsecurity from "../public/execsecurity.jpeg";
import cctv from "../public/cctv.jpeg";
import smen from "../public/smen.jpeg";
import smen1 from "../public/smen1.jpeg";

export default function Home() {
  return (
    <>
      <Head>
        <title>Welcome - GreenlandEstate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <main className="mv:m-auto">
        <section
          id="hero"
          className="xs:h-screen"
          style={{
            backgroundImage: "url('/gle.png')",
            backgroundRepeat: "no-repeat",
            backgroundPosition: "center",
            backgroundSize: "cover",
          }}
        >
          <div className="text-center text-white font-bold xs:flex-1 xs:text-center">
            <motion.div
              className="pt-36"
              initial={{ opacity: 0, scale: 0.5 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ duration: 1.5 }}
            >
              <span className="text-[20px] xs:text-[30px]">
                <p className="drop-shadow-md text-green-400 tracking-wide underline decoration-green-500/30 text-[2rem] xs:text-[5rem]">
                  GREENLAND ESTATE
                </p>
                <p className="pt-3 drop-shadow-lg">OFFICIAL WEBSITE</p>
              </span>
              <p className="text-transparent text-x xs:text-1xl xs:mt-5">
                Make Enquiry.
              </p>
              {/* DESKTOP VIEW CREATE USER-ACCOUNT BUTTON */}
              <div className="gap-2 text-center hidden xs:flex xs:justify-center xs:mt-10">
                <button className="bg-green-500 hover:bg-gradient-to-r hover:from-green-400 hover:to-green-600 text-teal-900 leading-0 px-6 py-2 rounded-md">
                  <Link href="/about">
                    <span className="text-[16px] text-white">About GLERA</span>
                  </Link>
                </button>
              </div>
              {/*   MOBILE VIEW CREATE USER-ACCOUNT BUTTON  */}
              <div className="flex gap-3 justify-center p-10">
                <div className="xs:hidden">
                  <button className="bg-green-500 leading-0 px-1 py-1 rounded-sm ">
                    <Link href="/about">
                      <span className="text-[10px]">About GLERA</span>
                    </Link>
                  </button>
                </div>
              </div>
            </motion.div>
          </div>
        </section>
        <section id="2">
          <div className="text-gray-500 text-center mt-10">
            __________________________________
          </div>

          <motion.div
            initial={{ opacity: 0, scale: 0.5 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 2.0 }}
            className="flex gap-2 font-bold justify-center items-center mt-10 mv:text-center mv:gap-1"
          >
            <Image
              alt=""
              src="/users.svg"
              width={30}
              height={30}
              className="mv:w-5 mv:h-5"
            />
            <h3 className="bold text-[13px]">SECURITY</h3>
            <Image
              alt=""
              src="/random-building.svg"
              width={30}
              height={30}
              className="w-30 h-30 mv:w-5 mv:h-5"
            />
            <h3 className="font-bold text-[13px]">DEVELOPMENT</h3>
            <Image
              alt=""
              src="/profitcurve.svg"
              width={30}
              height={30}
              className="mv:w-5 mv:h-5"
            />
            <h3 className="font-bold text-[13px]">ONENESS</h3>
          </motion.div>
        </section>
        {/* Our feature section starts here */}
        <section
          className="mt-10 xs:p-20 bg-gray-900 text-white"
          id="section1"
        >
          <motion.div
            initial={{ opacity: 0, scale: 0.5 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 2.0 }}
          >
            <h1 className="pb-5 mv:pt-10 mv:text-center mv:text-2xl xs:text-4xl tracking-wide underline decoration-gray-100/30">
              ABOUT GLERA
            </h1>
            <h2 className="font-bold text-center text-orange-500">GREENLAND RESIDENTS COMMUNITY DEVELOPMENT ASSOCIATION (GRCDA)</h2>
            {/* OUR FEATURE SECTION CONTENT 1*/}
            <div className="p-5 text-start xs:grid xs:grid-cols-5 items-center gap-3">
              <Image src={card} alt="" className="pb-5" />
              <p className="xs:col-span-4 text-[12px] xs:text-[12px] xs:mt-10 md:text-[16px]">
              Brief Background Report:
              Greenland Estate Residents Association was originally named and address as Olokonla village, Ajah.
              There were no village/Community dwellers but a group of individuals who bought their own landed properties directly from Olokonla & Olumegbon family.
              These individuals decided to come together and form a voluntary association named Greenland Estate Residents Association (GLERA) duly registered with the Corporate Affairs Commission (CAC). 
              Years later Greenland Residents Association decided to transmute into CDA and this was duly registered as GREENLAND RESIDENT Community Development Association with Eti Osa East Local Development Council Area, Lagos State on 30th October, 2012 with Registration number: <b className="text-green-500">EDELCDA/AR&SI.63VOL1-GRCDA. </b>
              Greenland Resident Community Development Association was equally registered at the State government level under the Ministry of Local Government And Community Affairs, Alausa, Ikeja.
              Greenland Resident Community Development Association has since inception witnessed four (4) successful regimes: 1st was headed by late Chief Abimbola Everett, 2nd was Chief Emmanuel Ileka, 3rd Captain Mbah and the 4th is the incumbent Chairman, Prince Adewale Taorid Ojora FICSSM FCICN.
              <Link href="/about" className="text-orange-500 text-[12px] xs:text-[12px] xs:mt-10 md:text-[16px]"> Read more...</Link>
              </p>
            </div>
            
            {/*  SECTION CONTENT 2 */}
            <div className="flex p-5 items-center xs:pt-10 xs:mt-20 xs:justify-evenly">
              <div className="text-white italic mv:text-[12px] text-[22px] md:text-[14px]">
                <p className="font-bold text-[24px] mv:text-[14px] md:text-[16px]">
                  CONSTANTLY DEVELOPING: <br />
                </p>
                <p>SECURITY.</p>
                <p>GOOD ROAD.</p>
                <p>ELECTRICITY.</p>
              </div>
              <div className="xs:flex">
                <div className="flex mv:pb-2 items-center space-x-4 w-[300px]">
                  <svg
                    width="54"
                    height="54"
                    viewBox="0 0 64 64"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <circle
                      cx="32"
                      cy="32"
                      r="32"
                      fill="#05B313"
                      fillOpacity="0.1"
                    />
                    <path
                      fillRule="evenodd"
                      clipRule="evenodd"
                      d="M31.565 47.8619C31.7422 47.9544 31.9403 48.0015 32.1384 47.9999C32.3365 47.9984 32.5331 47.9497 32.7119 47.8556L38.4205 44.8039C40.0393 43.941 41.307 42.9761 42.296 41.8527C44.4464 39.4051 45.6206 36.2813 45.5997 33.0602L45.5321 22.4352C45.5256 21.2114 44.7218 20.1194 43.5331 19.7224L32.9132 16.1593C32.2737 15.9428 31.573 15.9475 30.9448 16.1703L20.3652 19.8605C19.1829 20.2731 18.3936 21.373 18.4001 22.5983L18.4677 33.2155C18.4887 36.4413 19.7032 39.551 21.889 41.9735C22.8877 43.0812 24.1667 44.032 25.8032 44.8808L31.565 47.8619ZM30.0538 35.3743C30.2922 35.6034 30.6014 35.7163 30.9107 35.7132C31.22 35.7116 31.5276 35.5955 31.7628 35.3633L38.0014 29.213C38.4701 28.7501 38.4653 28.0064 37.9917 27.5498C37.5165 27.0933 36.7514 27.0964 36.2826 27.5593L30.893 32.8718L28.6862 30.7505C28.211 30.294 27.4475 30.2987 26.9772 30.7615C26.5084 31.2244 26.5133 31.9681 26.9884 32.4246L30.0538 35.3743Z"
                      fill="#05B313"
                    />
                  </svg>
                  <h1 className="font-bold text-[14px]">
                    Security
                  </h1>
                </div>
                <div className="flex items-center space-x-4 w-[300px]">
                  <svg
                    width="54"
                    height="54"
                    viewBox="0 0 64 64"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <circle
                      cx="32"
                      cy="32"
                      r="32"
                      fill="#05B313"
                      fillOpacity="0.1"
                    />
                    <path
                      d="M41.4696 35.7122C41.0552 36.1138 40.8648 36.6946 40.9592 37.2642L42.3816 45.1362C42.5016 45.8034 42.22 46.4786 41.6616 46.8642C41.1144 47.2642 40.3864 47.3122 39.7896 46.9922L32.7032 43.2962C32.4568 43.165 32.1832 43.0946 31.9032 43.0866H31.4696C31.3192 43.109 31.172 43.157 31.0376 43.2306L23.9496 46.9442C23.5992 47.1202 23.2024 47.1826 22.8136 47.1202C21.8664 46.941 21.2344 46.0386 21.3896 45.0866L22.8136 37.2146C22.908 36.6402 22.7176 36.0562 22.3032 35.6482L16.5256 30.0482C16.0424 29.5794 15.8744 28.8754 16.0952 28.2402C16.3096 27.6066 16.8568 27.1442 17.5176 27.0402L25.4696 25.8866C26.0744 25.8242 26.6056 25.4562 26.8776 24.9122L30.3816 17.7282C30.4648 17.5682 30.572 17.421 30.7016 17.2962L30.8456 17.1842C30.9208 17.101 31.0072 17.0322 31.1032 16.9762L31.2776 16.9122L31.5496 16.8002H32.2232C32.8248 16.8626 33.3544 17.2226 33.6312 17.7602L37.1816 24.9122C37.4376 25.4354 37.9352 25.7986 38.5096 25.8866L46.4616 27.0402C47.1336 27.1362 47.6952 27.6002 47.9176 28.2402C48.1272 28.8818 47.9464 29.5858 47.4536 30.0482L41.4696 35.7122Z"
                      fill="#05B313"
                    />
                  </svg>
                  <h1 className="font-bold text-[14px]">
                    Excellence
                  </h1>
                </div>
              </div>
            </div>
          </motion.div>
        </section>
        {/* Our feature section ends here */}
        <div className="xs:grid xs:grid-cols-5 items-center m-10">
          <div>
            <Image src={cm} alt="" width={200} className="rounded-full drop-shadow-lg pb-2"/>
            <h1 className="font">Current Chairman</h1>
            <p>Prince Adewale Taorid Ojora</p>
            <span>FICSSM FCICN</span>
          </div>
          <div className="xs:col-span-4 text-[12px] xs:text-[12px] xs:mt-10 md:text-[16px] mv:pt-5">
            <h1 className="text-green-700 font-bold text-lg">CHAIRMAN'S ACCEPTANCE SPEECH</h1>
            <p>
              Members of the Board of Trustees of our serene and great Estate,Members of the past EXCO, Members of the newly elected EXCO, The elders, 
              The land owning families ( Olumegbon & Olokonla) who are our traditional/ customary landlords,
              And of course all landlords & residents of the estate. 
              <span className="text-green-700 font-bold"> Congratulations Fellow Greenlanders</span> on this milestone achievement of emerging a stronger & better Greenland Estate from a keenly contested electioneering process.
              The outcome of this election is a victory for integrity, accountability, transparency, Victory for the rule of law, 
              Victory for all progressive minded Greenlanders who stood firm in upholding all known democratic principles in defense of our estate constitution which is the basis for our collective corporate existence as a legal entity .
              I salute the courage, dedication & commitment of our BOT led by Pastor Awelle Okonkwo in managing the situation effectively and ensuring timely completion of the democratic process.
              This is the birth of a new era in the administration of Greenland Estate. I stand here as the 5th elected chairman of Greenland Estate and 
              express my heart felt appreciation to everyone that has made this moment worthwhile for us to be able to gather again for the singular purpose of taking our estate to greater heights.
              While we are not oblivious of the recent developments in the estate,  it’s a long walk to freedom and institutionalized democracy .I hasten to emphasise that this election was geared towards having a more robust , cleaner , well organized and better community . I therefore take this election victory as a call to service and accountability of purpose.
              As leaders in our respective callings,  we occasionally find ourselves in situations that require we add to our proficiencies or we are faced with new experiences and opportunities  to propel a new thinking.
              However, the good thing in community relationships and community leadership is to be innovative and continuously hit the bulls eye for value added services, both in residential content and environmental aesthetics.
              Please let me state quickly that I will not shy away from the fact that we have to build on the successes of the past executives since inception of our estate. The honour is also for us to address any shortcomings and fill in the gaps.
              At this juncture, I wish to reiterate my firm commitment to our seven(7) points agenda tagged GEESIIF which is geared towards uplifting of all spheres of our estate.
              It is a clarion call that we all come on board to make this a reality and  achieve this purpose for the benefit of all.
              We will ensure monthly publication of the estate account and organize a quarterly town hall meeting for the presentation of stewardship of our administration in-line with our core values of integrity, accountability and transparency.
              <Link href="/about" className="text-orange-500"> See more...</Link>
            </p>
          </div>
        </div>

        <div className="xs:grid xs:grid-cols-4 xs:justify-items-center items-center m-10 xs:m-20">
          <Image src={exec} alt="Greenland Estate Executives" width={600} className="drop-shadow-lg pb-2"/>
          <div className="text-[12px] pb-5 text-center">
            <p className="text-[10] xs:text-[10px] md:text-[14px] italic">Newly elected Executive committee</p>
            <p className="text-[10] xs:text-[12px] md:text-[16px] font-bold">OUR WORD IS OUR BOND!</p>
          </div>
          <Image src={execsecurity} alt="" width={600} className="rounded-md drop-shadow-lg pb-2"/>
          <div className="xs:col-span-1 text-[12px] xs:text-[10px] md:text-[14px] text-center">
            <p className="font-bold">ESTATE MANAGEMENT ENGAGEMENT ON SECURITY</p>
            <p className="">
              Photo showing the Estate Management visit to the Nigerian Police, Ajiwe Division
            </p>
          </div>
        </div>

        <p className="text-center text-[20px] font-bold pb-2">ON SECURITY MATTERS</p>
        <div className="xs:grid xs:grid-cols-3 items-center m-10 xs:m-20 gap-3">
          <div className="text-[12px] pb-5 text-center">
            <Image src={cctv} alt="Greenland EstateCCTV" width={600} className="drop-shadow-lg rounded-lg pb-2"/>
            <p className="text-[10] xs:text-[10px] md:text-[14px] italic">Solar CCTV Donated by <span className="font-bold">SMARTCITY</span></p>
          </div>
          <div className="text-[12px] pb-5 text-center">
            <Image src={smen} alt="Greenland EstateCCTV" width={600} className="drop-shadow-lg rounded-lg pb-2"/>
            <p className="text-[10] xs:text-[10px] md:text-[14px] italic">Greenland Estate Security Men</p>
          </div>
          <div className="text-[12px] pb-5 text-center">
            <Image src={smen1} alt="Greenland EstateCCTV" width={600} className="drop-shadow-lg rounded-lg pb-2"/>
            <p className="text-[10] xs:text-[10px] md:text-[14px] italic">Estate Manager and Security officers</p>
          </div>
        </div>
        {/* CONTACT US */}
        <div className="mv:pt-10 mv:text-center">
          <span className="text-[24px]">For Enquiry / Complain</span> <br />
          <span className="text-[18px]">Kindly call or message</span>
        </div>
        <div className="pt-5 flex justify-center items-center gap-2">
          <Image src={call} alt="" width={30}/>
          <p>08033086816, 08068842004, 08059861875.</p>
        </div>
        <div className="xs:grid xs:grid-cols-1 items-center m-10">
          <h1 className="text-2xl text-center p-5">Find us on the map</h1>
          <iframe className="drop-shadow-md" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3964.3504174803315!2d3.6081006!3d6.477224499999999!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x103bf989dec3f6b3%3A0x3938c3d0a4395a1b!2sGreenland%20Estate%2C%20Eti-Osa%20106104%2C%20Lekki%2C%20Lagos%2C%20Nigeria!5e0!3m2!1sen!2shu!4v1699565469246!5m2!1sen!2shu" style={{ position: 'relative', width: '100%', height: '100vh' }} width="600" height="450" loading="lazy"></iframe>
        </div>
      </main>
    </>
  );
}
